FROM postgres:12-alpine

LABEL name "Alan Tai"
LABEL email "gogistics@gogistics-tw.com"

# copy required files into img
COPY ./infra/scripts/init/postgres.sh /docker-entrypoint-initdb.d/

EXPOSE 5432
